FROM python:3.10-slim

RUN apt-get update && apt-get install -y cron

WORKDIR /app

COPY cronjobs /etc/cron.d/cronjobs
RUN chmod 0644 /etc/cron.d/cronjobs
RUN touch /var/log/cron.log
CMD cron && tail -f /var/log/cron.log
