FROM ubuntu:20.04

# Отключаем запросы пользовательского ввода во время сборки образа
ENV DEBIAN_FRONTEND=noninteractive

COPY cronjobs /etc/cron.d/cronjobs

RUN chmod 0644 /etc/cron.d/cronjobs && \
    touch /var/log/cron.log && \
    apt-get update && \
    apt-get -y install cron

CMD cron && tail -f /var/log/cron.log
